services:

  mongo-service: # Id interno del servicio en mongo
    image: mongo
    container_name: mitocode-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mitocode
      MONGO_INITDB_ROOT_PASSWORD: mitocode
      MONGO_INITDB_DATABASE: mitocode
    volumes:
      - ./mongo-entry/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    ports: 
      - 27017:27017
    networks:
      - mitocode

  mongo-express:
    image: mongo-express
    container_name: mitocode-mongo-express
    depends_on:
      - mongo-service
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mitocode
      ME_CONFIG_MONGODB_ADMINPASSWORD: mitocode
      ME_CONFIG_MONGODB_URL: mongodb://mitocode:mitocode@mongo-service:27017
    networks:
      - mitocode

  # vault:
  #   image: hashicorp/vault
  #   container_name: mitocode-vault
  #   environment:
  #     VAULT_DEV_ROOT_TOKEN_ID: '00000000-0000-0000-0000-000000000'
  #   ports:
  #     - 8200:8200
  #   networks:
  #     - mitocode

  postgres:
    image: postgres:13.1-alpine
    container_name: mitocode-postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: mitocode
      POSTGRES_PASSWORD: mitocode
      POSTGRES_DB: mitocode
    networks:
      - mitocode

networks:

  mitocode:
    name: mitocode-network