services:

  mongo-service: # Id interno del servicio en mongo
    image: mongo
    container_name: mitocode-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mitocode
      MONGO_INITDB_ROOT_PASSWORD: mitocode
      MONGO_INITDB_DATABASE: mitocode
    volumes:
      - ./mongo-entry/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    ports: 
      - 27017:27017
    networks:
      - mitocode

  mongo-express:
    image: mongo-express
    container_name: mitocode-mongo-express
    depends_on:
      - mongo-service
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mitocode
      ME_CONFIG_MONGODB_ADMINPASSWORD: mitocode
      ME_CONFIG_MONGODB_URL: mongodb://mitocode:mitocode@mongo-service:27017
    networks:
      - mitocode

  # vault:
  #   image: hashicorp/vault
  #   container_name: mitocode-vault
  #   environment:
  #     VAULT_DEV_ROOT_TOKEN_ID: '00000000-0000-0000-0000-000000000'
  #   ports:
  #     - 8200:8200
  #   networks:
  #     - mitocode

  postgres:
    image: postgres:13.1-alpine
    container_name: mitocode-postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: mitocode
      POSTGRES_PASSWORD: mitocode
      POSTGRES_DB: mitocode
    networks:
      - mitocode

  mysql-keycloak:
    image: mysql
    container_name: mitocode-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_pwd
      MYSQL_DATABASE: keycloak
      MYSQL_USER: admin
      MYSQL_PASSWORD: mitocode-pwd
    ports:
      - 3306:3006
    networks:
    - mitocode    

  keycloak:
    image: quay.io/keycloak/keycloak:19.0.1
    container_name: mitocode-keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: mysql
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: mitocode-pwd
      KC_DB_URL_HOST: mysql-keycloak
      KC_DB_URL_PORT: 3306
      KC_DB_SCHEMA: keycloak
    ports:
      - 8080:8080
    depends_on:
      - mysql-keycloak
    command: start-dev
    networks:
    - mitocode        

  prometheus:
    image: prom/prometheus
    container_name: mitocode-prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/config/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
    - mitocode     

  grafana:
    image: grafana/grafana-oss
    container_name: mitocode-grafana
    ports:
      - 3000:3000
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_SERVER_DOMAIN: localhost
    networks:
    - mitocode  
    
networks:

  mitocode:
    name: mitocode-network