services:

  mongo-service: # Id interno del servicio en mongo
    image: mongo
    container_name: mitocode-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mitocode
      MONGO_INITDB_ROOT_PASSWORD: mitocode
      MONGO_INITDB_DATABASE: mitocode
    volumes:
      - ./mongo-entry/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    ports: 
      - 27017:27017
    networks:
      - mitocode

  mongo-express:
    image: mongo-express
    container_name: mitocode-mongo-express
    depends_on:
      - mongo-service
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mitocode
      ME_CONFIG_MONGODB_ADMINPASSWORD: mitocode
      ME_CONFIG_MONGODB_URL: mongodb://mitocode:mitocode@mongo-service:27017
    networks:
      - mitocode

  # vault:
  #   image: hashicorp/vault
  #   container_name: mitocode-vault
  #   environment:
  #     VAULT_DEV_ROOT_TOKEN_ID: '00000000-0000-0000-0000-000000000'
  #   ports:
  #     - 8200:8200
  #   networks:
  #     - mitocode

  postgres:
    image: postgres:13.1-alpine
    container_name: mitocode-postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: mitocode
      POSTGRES_PASSWORD: mitocode
      POSTGRES_DB: mitocode
    networks:
      - mitocode

  mysql-keycloak:
    image: mysql
    container_name: mitocode-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_pwd
      MYSQL_DATABASE: keycloak
      MYSQL_USER: admin
      MYSQL_PASSWORD: mitocode-pwd
    ports:
      - 3306:3006
    networks:
    - mitocode    

  keycloak:
    image: quay.io/keycloak/keycloak:19.0.1
    container_name: mitocode-keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: mysql
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: mitocode-pwd
      KC_DB_URL_HOST: mysql-keycloak
      KC_DB_URL_PORT: 3306
      KC_DB_SCHEMA: keycloak
    ports:
      - 8080:8080
    depends_on:
      - mysql-keycloak
    command: start-dev
    networks:
    - mitocode        

  prometheus:
    image: prom/prometheus
    container_name: mitocode-prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/config/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
    - mitocode     

  grafana:
    image: grafana/grafana-oss
    container_name: mitocode-grafana
    ports:
      - 3000:3000
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_SERVER_DOMAIN: localhost
    networks:
    - mitocode  
    
  loki:
    image: grafana/loki
    container_name: mitocode-loki
    ports:
      - 3100:3100
    networks:
      - mitocode

  zipkin:
    image: ghcr.io/openzipkin/zipkin-slim
    container_name: mitocode-zipkin
    ports:
      - 9411:9411
    environment:
      - STORAGE_TYPE=mem
    networks:
      - mitocode

  zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: mitocode-kafka-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - mitocode

  broker:
    image: confluentinc/cp-kafka
    container_name: mitocode-kafka-broker
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT, PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092, PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_REPLICATION_FACTOR: 1
    networks:
      - mitocode

  mongo-service-kafka: # Id interno del servicio en mongo
    image: mongo
    container_name: mitocode-mongo-kafka
    environment:
      MONGO_INITDB_ROOT_USERNAME: mitocode
      MONGO_INITDB_ROOT_PASSWORD: mitocode
      MONGO_INITDB_DATABASE: mitocode
    ports: 
      - 27018:27017
    networks:
      - mitocode

  mongo-express-kafka:
    image: mongo-express
    container_name: mitocode-mongo-express-kafka
    depends_on:
      - mongo-service-kafka
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mitocode
      ME_CONFIG_MONGODB_ADMINPASSWORD: mitocode
      ME_CONFIG_MONGODB_URL: mongodb://mitocode:mitocode@mongo-service-kafka:27017
    networks:
      - mitocode

networks:

  mitocode:
    name: mitocode-network